$shell( dirname $(abspath $(lastword $(MAKEFILE_LIST))))


CACHE_DIR := ${TOP_DIR}/cache.d
SRC_DIR   := ${TOP_DIR}/src

GCC_VERSION=11.1.0
GCC_TARGZ=gcc-${GCC_VERSION}.tar.gz
GDB_VERSION=5.2.1
GDB_TARGZ=gdb-${GDB_VERSION}.tar.gz
BINUTILS_VERSION=2.36.1
BINUTILS_TARGZ=binutils-${BINUTILS_VERSION}.tar.gz

INSTALL_DIR=${TOP_DIR}/install


CACHED_GCC=${CACHE_DIR}/${GCC_TARGZ}
CACHED_BINUTILS=${CACHE_DIR}/${BINUTILS_TARGZ}
CACHED_GDB=${GDB_TARGZ}
