#! /bin/bash
set -e
set -x

cd ../cache.d

rm -f gcc-11.1.0.tar.gz
wget https://ftp.gnu.org/gnu/gcc/gcc-11.1.0/gcc-11.1.0.tar.gz

rm -rf binutils-2.36.tar.gz
wget https://ftp.gnu.org/gnu/binutils/binutils-2.36.tar.gz

rm -rf gdb-10.2.tar.gz
wget https://ftp.gnu.org/gnu/gdb/gdb-10.2.tar.gz

